### ISSUE TITLE
Failed to open file “resources/mcskineditor.gresource”

### ISSUE THREAD

**Issue by Phant80m** [RedGradient/MinecraftSkinEditor#1]
![image](https://github.com/RedGradient/MinecraftSkinEditor/assets/70614900/d7e48c13-5e7a-45af-b7f7-1b9c110ff1ef)

file does not exist!

**Comment by RedGradient** [comment]
Hi! Thank you for your interest in my humble project!

At first time the project should be run with `make build` command, that will generate the necessary resource file. After that you can use `cargo run`.

I've also added this information in readme.
